language: elixir
elixir:
  - 1.1.0
otp_release:
  - 17.5
  - 18.0
services: mysql
notifications:
  recipients:
    - elixmoon@gmail.com
    - jquadrin@gmail.com
sudo: false
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
