language: elixir
elixir:
  - 1.2.6
otp_release:
  - 18.0
  - 19.1
services: mysql
notifications:
  recipients:
    - elixmoon@gmail.com
    - jquadrin@gmail.com
sudo: false
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
